### ISSUE TITLE
Cannot import tqdm

### ISSUE THREAD

**Issue by robertodr** [sagemathinc/csi-quantum-chemistry#1]
Hello, thanks for creating this image for CoCalc.

The installation of tqdm seems corrupt. I cannot import the module, neither in a notebook, nor in a terminal. However, doing `conda list` shows that the package is installed.

**Comment by haraldschilly** [comment]
So, I don't know why it is there (magic? some indirect dependency?) but I recall I added tqdm after I built it the last time. Simply, because I saw it took a minute to do the calculation in the loop in the example file. Sorry for the confusion.
